# Generated by Django 5.2.4 on 2025-07-04 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('administrativo', 'Administrativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_publicados', to='viajes.usuario'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='cupos_disponibles',
            field=models.PositiveIntegerField(),
        ),
    ]
